In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

In [9]:
new = pd.read_csv('concatenated_data.csv')
vocab = list(set(np.genfromtxt('dict_words.txt',dtype=str,delimiter=',')))

In [10]:
X_train, X_test, y_train, y_test = train_test_split(new['Text'], new['SITE'], random_state = 1)

In [11]:
min_dff = np.arange(3,30)
output = []
from sklearn import naive_bayes

for i in range(0,len(min_dff)):
    vect = CountVectorizer(min_df = min_dff[i], ngram_range= (1,1), stop_words = 'english',vocabulary=vocab).fit(X_train)
    #vect=CountVectorizer(tokenizer=LemmaTokenizer(), min_df = min_dff[i], stop_words = 'english').fit(X_train)
    #vect.vocabulary_.pop('cm')
    X_train_vectorized = vect.transform(X_train)
    X_test_vectorized = vect.transform(X_test)
    clfrNB = naive_bayes.MultinomialNB()
    clfrNB.fit(X_train_vectorized,y_train)
    predicted = clfrNB.predict(X_test_vectorized)
    output.append(np.mean(predicted == y_test))

In [12]:
output

[0.9401408450704225,
 0.9401408450704225,
 0.9401408450704225,
 0.9401408450704225,
 0.9401408450704225,
 0.9401408450704225,
 0.9401408450704225,
 0.9401408450704225,
 0.9401408450704225,
 0.9401408450704225,
 0.9401408450704225,
 0.9401408450704225,
 0.9401408450704225,
 0.9401408450704225,
 0.9401408450704225,
 0.9401408450704225,
 0.9401408450704225,
 0.9401408450704225,
 0.9401408450704225,
 0.9401408450704225,
 0.9401408450704225,
 0.9401408450704225,
 0.9401408450704225,
 0.9401408450704225,
 0.9401408450704225,
 0.9401408450704225,
 0.9401408450704225]

In [13]:
    training_accuracy = clfrNB.score(X_train_vectorized, y_train)
    test_accuracy = clfrNB.score(X_test_vectorized, y_test)
    
    print("Accuracy on training data: %0.2f" %(training_accuracy))
    print("Accuracy on test data: %0.2f" %(test_accuracy))

Accuracy on training data: 0.94
Accuracy on test data: 0.94


In [14]:
def print_top10(vectorizer, clf, class_labels):
    """Prints features with the highest coefficient values, per class"""
    feature_names = vectorizer.get_feature_names()
    for i, class_label in enumerate(class_labels):
        top10 = np.argsort(clf.coef_[i])[-10:]
        top10=top10[::-1]
        print("%s: %s" % (class_label,
              " ".join(feature_names[j] for j in top10)))

In [15]:
values, counts = np.unique(y_test,return_counts=True)
print_top10(vect, clfrNB, values)

BREAST: breast carcinoma margin tissue lymph tumor node left right invasive
COLON: tumor colon margin lymph nodes tissue polyp invasion adenocarcinoma distal
LUNG: lymph lung tumor node cell tissue lobe carcinoma cells right
OTHER: tumor left tissue right lymph cells nodes cell carcinoma thyroid
PROSTATE: prostate right left tissue lymph prostatic base seminal apex invasion


In [16]:
a = confusion_matrix(y_test, predicted, labels=values, sample_weight=None)
print(a)

[[76  0  2  0  0]
 [ 0 54  3  0  0]
 [ 0  0 58  2  1]
 [ 0  4  3 42  2]
 [ 0  0  0  0 37]]


In [17]:
values

array(['BREAST', 'COLON', 'LUNG', 'OTHER', 'PROSTATE'], dtype=object)

In [4]:
new = pd.read_csv('concatenated_data.csv')

In [5]:
new.head()

Unnamed: 0   SITE  PATIENT_DISPLAY_ID  \
0           0  COLON              451455   
1           1  COLON              541798   
2           2  COLON              347923   
3           3  COLON              405167   
4           4  COLON              411395   

                                                Text  
0  nan nan nan <CLINICAL INFO> A. RULE OUT SPRUE,...  
1  nan nan nan <CLINICAL INFO> HISTORY OF POLYP  ...  
2  nan nan nan CASE: GAO11-003406 PATIENT: **NAME...  
3  nan nan nan <CLINICAL INFO>  Cecal carcinoma, ...  
4  nan nan nan CASE: ***PATH-NUMBER[1] PATIENT: *...

In [31]:
type(vect.vocabulary_)

dict

In [34]:
del(vect.vocabulary_('cm'))

SyntaxError: can't delete function call (<ipython-input-34-dbbd7417fcc3>, line 1)

In [36]:
vect.vocabulary_.pop('cm')

219

In [37]:
vect.vocabulary_

{'00': 0,
 '07': 1,
 '08': 2,
 '10': 3,
 '100': 4,
 '11': 5,
 '12': 6,
 '13': 7,
 '14': 8,
 '15': 9,
 '16': 10,
 '17': 11,
 '18': 12,
 '19': 13,
 '1988': 14,
 '1a': 15,
 '1b': 16,
 '1c': 17,
 '20': 18,
 '2009': 19,
 '2010': 20,
 '2011': 21,
 '2012': 22,
 '2013': 23,
 '21': 24,
 '22': 25,
 '23': 26,
 '24': 27,
 '25': 28,
 '26': 29,
 '27': 30,
 '28': 31,
 '29': 32,
 '2a': 33,
 '2cm': 34,
 '30': 35,
 '31': 36,
 '35': 37,
 '3a': 38,
 '40': 39,
 '4000': 40,
 '45': 41,
 '48': 42,
 '50': 43,
 '5cm': 44,
 '60s': 45,
 '67': 46,
 '7th': 47,
 '80': 48,
 '88305': 49,
 '88307': 50,
 '88309': 51,
 '90': 52,
 '95': 53,
 'a1': 54,
 'a10': 55,
 'a11': 56,
 'a12': 57,
 'a16': 58,
 'a2': 59,
 'a3': 60,
 'a4': 61,
 'a5': 62,
 'a6': 63,
 'a7': 64,
 'a8': 65,
 'a9': 66,
 'aaa': 67,
 'abnormal': 68,
 'absent': 69,
 'abundant': 70,
 'ac': 71,
 'according': 72,
 'acinar': 73,
 'activity': 74,
 'acute': 75,
 'addenda': 76,
 'addendum': 77,
 'addendumcomment': 78,
 'addendumdiagnosis': 79,
 'additional': 80,
 'a

In [8]:
output = []
min_dff = np.arange(3,30)
from sklearn.linear_model import LogisticRegression

for i in range(0,len(min_dff)):
    vect = CountVectorizer(min_df = min_dff[i], ngram_range= (1,1), stop_words = 'english').fit(X_train)
    #vect=CountVectorizer(tokenizer=LemmaTokenizer(), min_df = min_dff[i], stop_words = 'english').fit(X_train)
    X_train_vectorized = vect.transform(X_train)
    X_test_vectorized = vect.transform(X_test)
    log = LogisticRegression(penalty='l2')
    log.fit(X_train_vectorized,y_train)
    predicted = log.predict(X_test_vectorized)
    output.append(np.mean(predicted == y_test))

In [11]:
    training_accuracy = log.score(X_train_vectorized, y_train)
    test_accuracy = log.score(X_test_vectorized, y_test)
    
    print("Accuracy on training data: %0.2f" %(training_accuracy))
    print("Accuracy on test data: %0.2f" %(test_accuracy))

Accuracy on training data: 1.00
Accuracy on test data: 0.92


In [19]:
values, counts = np.unique(y_test,return_counts=True)
print_top10(vect, log, values)

BREAST: breast axillary ductal axilla reactive her2 noted patient core note
COLON: colon adenocarcinoma colonic sigmoid mucinous polyps laparoscopic pelvic request submitted
LUNG: lung ttf pleural bronchial cell egfr pulmonary malignancy proximal touch
OTHER: bladder papillary compatible epithelial fna feb thinprep lymphoma 22 skin
PROSTATE: prostate prostatic gleason age surface benign squamous posterior blocks representative


In [21]:
from sklearn import svm
for i in range(0,len(min_dff)):
    vect = CountVectorizer(min_df = min_dff[i],ngram_range= (1,2), stop_words = 'english').fit(X_train)
    #vect=CountVectorizer(tokenizer=LemmaTokenizer(), min_df = min_dff[i], stop_words = 'english').fit(X_train)
    X_train_vectorized = vect.transform(X_train)
    X_test_vectorized = vect.transform(X_test)
    clfrSVM = svm.SVC(kernel = 'rbf', C = 22)
    clfrSVM.fit(X_train_vectorized, y_train)
    predicted = clfrSVM.predict(X_test_vectorized)
    output.append(np.mean(predicted == y_test))

In [ ]:
training_accuracy = clfrSVM.score(X_train_vectorized, y_train)
test_accuracy = clfrSVM.score(X_test_vectorized, y_test)

In [22]:
print("Accuracy on training data: %0.2f" %(training_accuracy))
print("Accuracy on test data: %0.2f" %(test_accuracy))

Accuracy on training data: 0.99
Accuracy on test data: 0.89


In [14]:
df = pd.DataFrame(data=X_test)
df['Actual FC'] = y_test
df['Predicted FC'] = log.predict(X_test_vectorized)

df_train = pd.DataFrame(data=X_train)
df_train['Actual FC'] = y_train
df_train['Predicted FC'] = log.predict(X_train_vectorized)

df_combined = pd.concat([df, df_train])
df_combined.sort_index(inplace=True)

df_combined.to_excel("E10_output(with outliers).xlsx")

IllegalCharacterError: 

In [36]:
df_combined.iloc[12,:]

Text            nan nan nan **NAME[ZZZ,YYY M] MD     **NAME[XX...
Actual FC                                                   COLON
Predicted FC                                                COLON
Name: 12, dtype: object

In [23]:
df_combined.Text[18]

'nan nan nan <CLINICAL HX> A) Cecal mass bxs. B) Rectal p. i. Adenoma vs hyperplasia. Submitted ICD9 codes 211.4, 211.3. STAT reading requested.    <HISTOLOGY COMMENT>     <GROSS> A.  In formalin labeled with the patient\'s name and "A" are approximately seven 1-3 mm pieces of tan tissue. Submitted as received in cassette A. B.  In formalin labeled with the patient\'s namd and "B" is a 5 mm piece of tan tissue. Submitted as received in cassette B.   <COMMENT>   <MICROSCOPIC> Six slides are examined (block A was exhausted).  <FINAL DX>  A.  CECUM, BIOPSIES DESIGNATED MASS:  ADENOCARCINOMA, INVASIVE, LOW-GRADE (WELL TO MODERATELY DIFFERENTIATED)  IN THIS MATERIAL.  B.  RECTAL POLYP:  TUBULAR ADENOMA.   <ANCILLARY STUDIES>   <EXTERNAL CONSULTATION>   <INTRADEPARTMENTAL CONSULTATION> The case was reviewed intradepartmentally.  <NOTIFICATION>   <PRELIM DX>   <CHECKLIST>   <IMMUNOHISTOCHEMISTRY>   <INDICATIORS>   <SPECIAL STAINS> nan nan nan nan nan'

In [26]:
df_combined.to_csv("E10_output(with outliers).csv")